[repository]
name = "notify-dismiss"
authors = ["ItsDrike"]
commit_pins = [
  [
    "1c460e98f870676b15871fe4e5bfeb1a32a3d6d8",
    "004e8c3afeb4aed9038b539a34b775db8a2d7a17",
  ], # 0.36.0
]

[notify-dismiss]
description = "Add notifydismiss hyprctl command"
authors = ["ItsDrike"]
output = "notify-dismiss.so"
build = ["make all"]
