[repository]
name = "notify-dismiss"
authors = ["ItsDrike"]
commit_pins = [
  [
    "1c460e98f870676b15871fe4e5bfeb1a32a3d6d8",
    "13d716046562cf2081cd8679562597ccf33f033d",
  ], # 0.36.0
]

[notify-dismiss]
description = "Add notifydismiss hyprctl command"
authors = ["ItsDrike"]
output = "notify-dismiss.so"
build = ["make all"]
