[repository]
name = "notify-dismiss"
authors = ["ItsDrike"]
commit_pins = [
  [
    "1c460e98f870676b15871fe4e5bfeb1a32a3d6d8",
    "ea8ab2f61c8fa58038df184f8cda64dc7695fe5f",
  ], # 0.36.0
]

[notify-dismiss]
description = "Add notifydismiss hyprctl command"
authors = ["ItsDrike"]
output = "notify-dismiss.so"
build = ["make all"]
