[repository]
name = "notify-dismiss"
authors = ["ItsDrike"]
commit_pins = [
  [
    "1c460e98f870676b15871fe4e5bfeb1a32a3d6d8",
    "b5378950c302e8570b6067797eefdd3b54f50851",
  ], # 0.36.0
]

[notify-dismiss]
description = "Add notifydismiss hyprctl command"
authors = ["ItsDrike"]
output = "notify-dismiss.so"
build = ["make all"]
